import name_checker


def sieve(names):
    sieved_names = {race: [] for race in range(-1, 5)}
    for name in names:
        race = name_checker.name_check(name)
        sieved_names[race].append(name)

    print(f'whi_names = {sieved_names[0]}')
    print(f'bla_names = {sieved_names[1]}')
    print(f'his_names = {sieved_names[2]}')
    print(f'asi_names = {sieved_names[3]}')
    print(f'oth_names = {sieved_names[4]}')
    print(f'oov_names = {sieved_names[-1]}')


print('sieve expanded european american names')
names = ['Laurinda', 'Jarett', 'Lucy', 'Laurențiu', 'Darrieussecq', 'Rachel--', 'Elaine', '-Alan', 'Carlysle', 'Kristinn', 'JoAnne', 'Geoffrey', 'RyanAir', 'Nancye', 'Rachelle', '-Amanda', 'Andrewartha', 'Kristina', 'Adamle', 'Melissa', 'Pauly', 'MacAndrew', 'Laurien', 'Koshy', 'Cynthia', 'Sara', 'NDN', 'Elissa', 'Julieanne', 'Kathleen', 'Adam4Adam', 'Ryans', 'Alaniz', 'Ellens', 'Bobb', 'Hannah', 'Joanie', '-Peter', 'Jackky', 'Brooke', 'Susan', 'Elleby', 'Frank--', 'Kristyn', 'Doug', 'Syrett', 'Kristinsson', 'Laurin', 'Paulão', '-Justin', 'Ian', 'McRyan', 'Carolyn', 'Carolynn', 'Ellenson', 'Franklyn', 'Corey', 'Kieran', 'Michael', 'Ellenor', 'Kristína', 'Kristiina', 'Rachell', 'Jessica--', 'Jack--', 'Brandon', 'Mauren', 'Bobbye', 'Greggy', 'Peten', 'Julie', 'Dave', 'Kevin', 'Clarrie', 'Adamczak', '-(Peter', 'Paule', 'Aidan', 'Jessica', 'Delanie', 'kristen', 'Kristine', 'Kristi', 'Roge', 'Koshu', 'McAdam', '-Nancy', 'Larrie', 'brendan', 'Kristín', 'Stuart', 'Laurene', 'Justin.tv', 'Deanne', 'Kristu', 'Lauragais', 'Geoff', 'Frankweiler', 'Kellison', 'Jacklyn', 'Myler', 'Rogero', '-Andrew', 'Leimove', '-Adam', 'Peteghem', 'Justi', 'Jack-', '-Roger', 'Kristensen', 'Janessa', 'Peter--', 'Jackdaw', 'Ricki', 'Laurey', 'Laurila', "O'Ryan", 'Peterle', 'Harrie', 'Laurenzi', 'Lyndall', 'Cheryl', 'Elison', 'Slevin', 'Laur', 'Jackyl', 'Uwharrie', 'Nancowry', 'Kristijan', 'Laurenz', 'Koger', '-Anne', '-Rebecca', 'Jeffy', 'Bryan', '-Paul', 'Rob', 'Sean', 'Noeleen', 'Frankau', 'Frankley', 'Peterka', "d'Anne", 'Kirsten', 'Franky', 'Kristóf', 'Nancys', '-Sarah', 'Keith', 'Johnie', 'Andrewes', 'Ellena', 'Sarahs', 'Rachele', 'Paul_The_Nerd', 'Mustin', 'Stephany', 'Adamek', 'Adamec', '-Frank', 'Paulínia', 'Justineau', 'McAndrew', 'Bretts', 'Adami', 'Cullison', '-Kevin', 'Collison', '-Greg', '-Emily', 'Skerrett', 'Hoger', 'Boger', 'Rogerio', 'Tristin', 'MaryAnne', '-Ryan', 'Ollison', 'Adam-', 'Errett', 'Kathrynne', 'Petek', 'Shawn', 'Karen', 'Peterhof', 'Gregg', 'Grega', 'Rebeccah', 'Andys', 'Tristen', 'Rebecca', 'Ryann', 'Keithley', 'Ciaron', 'Randall', 'Carlye', 'Rachels', 'Jerrett', 'alison', '-Stephanie', 'Gregynog', 'he’d', 'kristin', 'Darragh', 'Kelleher', 'Karrie', 'Sharlene', 'LeeAnne', 'Kathy', 'Garrie', 'Stephen', 'Geof', 'Rogell', 'Frankl', 'DeFrank', 'Carlyn', 'Louise', 'Paull', 'Darrell', 'Justina', 'Paulig', 'Annee', 'Pauls', 'meredith', 'Mollison', 'Jackiw', 'Danielle', 'Treynor', '-Rachel', 'David', 'Laurenpolo.us', 'Jackdaws', 'Gustin', 'Moger', '-Stephen', 'Paulk', 'Justine', 'MacAdam', 'Emma', 'Anneka', 'Rolison', 'Lisabeth', 'Janell', 'Helen', 'Jacko', 'Suzanne', 'Jessa', 'Kristinehamn', 'Sarah--', 'Jeremih', 'Pamela', 'Carolynne', 'Samantha', 'Willison', 'LaLaurie', 'Brend', 'Julissa', 'Justiz', 'Kristýna', 'Frankia', 'Jackée', 'Roget', 'MaryEllen']
sieve(names)
print()

print('sieve expanded african american names')
names = ['Leitrim', 'Alfonzo', 'Beamont', 'Ivette', 'Lamarr', 'Lamond', 'Matthijs', 'Deroy', 'Mugisha', 'Vontae', 'bavette', 'Mims', 'Thaddäus', 'Audette', 'Haki', 'LaWanda', 'Hamza', 'Jamam', 'Theoden', 'Lamarckism', 'Sharmaine', 'Dorrance', 'Kareema', 'Lamai', 'Lamarckian', 'Jamali', 'Iolanda', 'Sylvette', 'Benjy', 'Barnell', 'ACDA', 'Lawrance', 'Zeisha', 'Derrick', 'Terence', 'alonzo', '2/9', 'Lusty', 'Jameel', 'Marnell', 'Delamont', 'Busty', 'Abdulrasheed', 'Malika', 'Rashawn', 'Jabbar', 'Holanda', 'Nairobi', 'Azizi', 'Ruggs', 'Jasmin', 'Clarance', 'Rasheeda', 'Khaliq', 'Rosaly', 'Rabil', 'Monaghan', 'Lamare', 'Lonny', 'Jame', 'You’re', 'Nance', 'OLB', 'Jameer', 'Meisha', 'Eboni', 'Zambia', 'Theodo', 'Aish', 'Mattheus', 'Bledsoe', 'Kurnell', 'Lamarca', 'Maalik', 'Alvah', 'Amee', 'Raquela', 'Hakimi', 'Carnell', 'Terrance', 'Rashid', 'Zaina', 'Theoi', 'Leroi', 'Jalen', 'Kenyah', 'Kyla', 'Botswana', 'Cuvette', 'torrance', 'Jolanda', 'Jamek', 'Malawi', 'Lowrance', 'Conaghan', 'Lawerence', 'Sibony', 'Wilmont', 'Uganda', 'Rolanda', 'Cedrick', 'Purnell', 'Varnell', 'Jamet', 'Talhah', 'Dahir', 'Lionello', 'Jamalullail', 'Hamel', 'Rashad', 'Rashaun', 'Lamoni', 'isha', 'Charmaine', 'Leisha', 'Jamanxim', 'KrystlE', 'Tyron', 'Kalonzo', 'Tyreke', 'Theognis', 'tyrone', 'Jamahl', 'Torrence', 'Bilhah', 'Lamač', 'Donya', 'Bea', 'Hareem', 'Jasmina', 'Zimbabwe', 'Jamalul', 'Tyrer', 'Orvin', 'jasmin', 'ebon', 'Jeromy', 'Yayla', 'Arnell', 'Jale', 'Jaleh', 'Ayisha', 'Blaye', 'Nanette', 'Yarnell', 'Offaly', 'Nasri', 'Nyree', 'Jameh', 'McAlmont', "A'isha", 'Leeroy', 'jasmine', 'Kasmin', 'Lamacq', 'Ionel', 'Juanda', 'Sexy', 'Jasmyn', 'Shaylee', 'Concurrence', 'Richie', 'Nasheed', 'Deterrence', 'leroy', 'IL-3', 'lionel', 'Lamarcus', 'Neisha', 'Jazmin', 'LeRoy', 'Cuonzo', 'Jerold', 'Rance', 'Kilonzo', 'Zakim', 'Lamon', 'Lyonel', 'Jamesy', 'Jaleel', 'Gerard', 'Tarrance', 'LaKeisha', 'Kamran', 'McClymont', 'Dreem', 'Elyakim', 'Ebon', 'Tyrell', 'Dwaine', 'Jero', 'Rasheedha', 'Waheed', 'Geroy', 'Fermanagh', 'Seance', 'Rosalía', 'Jermain', 'K.J.', 'Tyreese', 'Eamont', 'Jasminum', 'Hakimullah', 'Aleisha', 'Myron', 'Lamo', 'Jamey', '-4.5', 'Kenyan', 'Lily', 'Gerome', 'Jasmines', 'Theos', 'Aishu', 'Germaine', 'Tyreek', 'Armagh', 'Javon', 'Lia', 'Nekeisha', 'Rasheem', 'Tanzania', 'Larnell', 'Jama’at', 'yolanda', 'Gabey', 'Jerod', 'Tyro', 'Elvin', 'Maliks', 'Lorence', 'Jaylah', 'Laina', 'Aishah', 'Jisha', 'Nude', 'jerome', 'Lamarre', "O'Donel", 'Jamaïcan', 'yvette', 'Khursheed', 'Jamea', 'Yasmine', 'Evette', 'Maliksi', 'Lisha', 'Lero', 'Rahim', 'Derome', 'Finley', 'Ronay', 'Cavan', 'Hamzeh', 'Ronel', 'Tahir', 'PYTHON', 'Jermuk', 'McLeroy', 'Aniko', 'Geisha', 'Jeanette', 'Theodoxus', 'Quartermaine', 'Theodicy', 'Durrance', 'Rasha', '175k', 'Tyrel', "Jama'a", 'ebony', 'keisha', 'Vanette']
sieve(names)
